from setuptools import setup, find_packages

version = '2.2-dev'

install_requires = [
    'ZODB3',
    'dolmen.app.authentication',
    'dolmen.app.breadcrumbs',
    'dolmen.app.layout',
    'dolmen.app.security',
    'dolmen.authentication',
    'dolmen.beaker',
    'dolmen.container',
    'dolmen.content',
    'dolmen.forms.base',
    'dolmen.forms.wizard',
    'dolmen.security.policies',
    'dolmen.menu',
    'fanstatic',
    'grok',
    'grokcore.chameleon',
    'grokcore.component',
    'grokcore.layout',
    'grokcore.message',
    'grokcore.registries',
    'grokcore.site',
    'grokcore.traverser',
    'grokcore.viewlet',
    'grokui.admin',
    'hurry.workflow',
    'js.bootstrap',
    'js.bootstrapdatepicker',
    'js.jquery',
    'js.jquery_tablesorter',
    'js.jquery_tools',
    'lxml',
    'martian',
    'elementtree',
    'megrok.pagetemplate',
    'megrok.resourceviewlet',
    'megrok.z3ctable',
    'reportlab',
    'repoze.filesafe',
    'setuptools',
    'transaction',
    'uvc.catalog',
    'uvc.homefolder',
    'uvc.layout',
    'uvc.validation',
    'uvc.widgets',
    'z3c.schema2xml',
    'uvc.staticcontent',
    'z3c.table',
    'zeam.form.base',
    'zeam.form.composed',
    'zeam.form.layout',
    'zeam.form.table',
    'zeam.form.viewlet',
    'zeam.form.ztk',
    'zope.annotation',
    'zope.app.appsetup',
    'zope.app.homefolder',
    'zope.app.locales',
    'zope.app.pagetemplate',
    'zope.app.wsgi',
    'zope.authentication',
    'zope.browsermenu',
    'zope.catalog',
    'zope.catalog',
    'zope.component',
    'zope.container',
    'zope.dottedname',
    'zope.dublincore',
    'zope.event',
    'zope.fanstatic',
    'zope.generations',
    'zope.i18n [compile]',
    'zope.i18nmessageid',
    'zope.interface',
    'zope.intid',
    'zope.lifecycleevent',
    'zope.pagetemplate',
    'zope.pluggableauth',
    'zope.publisher',
    'zope.schema',
    'zope.security',
    'zope.securitypolicy',
    'zope.sendmail',
    'zope.session',
    'zope.site',
    'zope.traversing',
    'zope.viewlet',
    'unittest2',
    'uvc.tbskin',
    'zope.app.testing',
    ]


tests_require = [
    'dolmen.security.policies',
    'elementtree',
    'formencode',
    'grokcore.layout',
    'js.jquery_maskmoney',
    'megrok.layout',
    'mock',
    'unittest2',
    'uvc.staticcontent',
    'uvc.tbskin',
    'uvc.validation',
    'z3c.table',
    'z3c.testsetup',
    'zope.app.publication',
    'zope.app.testing',
    'zope.browserpage',
    'zope.contentprovider',
    'zope.lifecycleevent',
    'zope.password',
    'zope.principalregistry',
    'zope.processlifetime',
    'zope.site',
    'zope.testbrowser [zope-functional-testing]',
    'zope.testing',
     ]


setup(name='uvcsite',
      version=version,
      description="",
      long_description="""\
""",
      # Get strings from http://www.python.org/pypi?%3Aaction=list_classifiers
      classifiers=[],
      keywords="",
      author="UVC-WebCommnunity",
      author_email="cklinger@novareto.de",
      url="http://uvwebcommunity.bg-kooperation.de/",
      license="ZPL",
      package_dir={'': 'src'},
      packages=find_packages('src', exclude=['ez_setup']),
      include_package_data=True,
      zip_safe=False,
      install_requires=install_requires,
      extras_require={'test': tests_require},
      entry_points = """
      [paste.app_factory]
      main = grokcore.startup:application_factory
      [paste.filter_app_factory]
      registries = uvcsite.registries:provide_registries
      [zodbupdate]
      renames = uvcsite.migration:classes_migration
      """,
      )
